In [1]:
#CSV파일
## pandas.read_csv("파일 경로(이름)")

import pandas as pd
import os

os.listdir("./DATA")

['df_excelwriter.xlsx',
 'df_sample.csv',
 'df_sample.json',
 'df_sample.xlsx',
 'df_sample_columns.json',
 'df_sample_index.json',
 'df_sample_no_index.csv',
 'df_sample_no_index.xlsx',
 'df_sample_records.json',
 'df_sample_split.json',
 'df_sample_values.json',
 'read_csv_sample.csv',
 'read_json_sample.json',
 'sample.html',
 'test.csv',
 'test.json',
 '남북한발전전력량.xlsx']

In [2]:
file_path = './DATA/read_csv_sample.csv'
print(file_path)

./DATA/read_csv_sample.csv

In [3]:
file_path2 = os.path.join('DATA','read_csv_sample.csv')
print(file_path2)

DATA\read_csv_sample.csv

In [4]:
df1 = pd.read_csv(file_path)
df1

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9

In [5]:
df2 = pd.read_csv(file_path,header=None)
df2

    0   1   2   3
0  c0  c1  c2  c3
1   0   1   4   7
2   1   2   5   8
3   2   3   6   9

In [6]:
df3 = pd.read_csv(file_path, index_col=None)
df3

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9

In [7]:
df4 = pd.read_csv(file_path, index_col='c0')
df4

    c1  c2  c3
c0
0    1   4   7
1    2   5   8
2    3   6   9

In [8]:
#  엑셀 파일
# pandas.read_excel("파일경로")

import pandas as pd
df1 = pd.read.excel('./DATA/남북한발전전력량.xlsx',engine = 'openpyxl')

df1.head

AttributeError: module 'pandas' has no attribute 'read'

In [ ]:
# JSON 파일

In [ ]:
# 웹에서 가져오기
##pandas.read_html("파일경로")

import pandas as pd
url = "./DATA/sample.html"
pd.read_html(url)