In [27]:
#CSV파일
## pandas.read_csv("파일 경로(이름)")

import pandas as pd
import os

os.listdir("./DATA")

['read_csv_sample.csv']

In [28]:
file_path = './DATA/read_csv_sample.csv'
print(file_path)

./DATA/read_csv_sample.csv

In [29]:
file_path2 = os.path.join('DATA','read_csv_sample.csv')
print(file_path2)

DATA\read_csv_sample.csv

In [30]:
df1 = pd.read_csv(file_path)
df1

   co  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9

In [31]:
df2 = pd.read_csv(file_path,header=None)
df2

    0   1   2   3
0  co  c1  c2  c3
1   0   1   4   7
2   1   2   5   8
3   2   3   6   9

In [32]:
df3 = pd.read_csv(file_path, index_col=None)
df3

   co  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9

In [33]:
df4 = pd.read_csv(file_path, index_col='c0')
df4

ValueError: Index c0 invalid